language: r
sudo: false
cache: packages
r:
  - oldrel
  - release
  - devel

r_github_packages:
  - rstats-db/DBI
  - rstats-db/DBItest

#   - hadley/testthat
#   - hadley/dplyr
#   - hadley/dbplyr
  
script:
  - |
    R CMD build .
    travis_wait 80 R CMD check MonetDBLite*tar.gz
  
addons:
  apt_packages:
    - pandoc

after_failure:
  - ./travis-tool.sh dump_logs
